### ISSUE TITLE
[BUG] UI Broken in 0.21.1

### ISSUE THREAD

**Issue by norman784** [wasmCloud/wash-archive#916] opened 2023-10-18 17:03 UTC
**Describe the bug**

When accessing the UI loads with an error

**To Reproduce**
1. Run command 'wash up --nats-websocket-port 4001'
2. Run other command 'wash ui --experimental'
2. Go to http://localhost:3030
3. Then an error is shown

**Screenshots**

![image](https://github.com/wasmCloud/wash/assets/204656/7f57d5c2-5810-486e-a3ee-42810f95cfee)

![image](https://github.com/wasmCloud/wash/assets/204656/a8c77205-ff57-4ae0-9063-88c7018504e1)

**Environment (please complete the following information) **
 - OS: MacOS
 - Shell zsh
 - wash Version 0.21.1

**Additional context**

Installed via cargo and brew, same issue. The version 0.20.2 works fine, didn't tried the previous pre-release version.

**Comment by connorsmith256** [comment] 2023-10-19 00:39
@lachieh I was able to reproduce with a chromium based browser (Arc)
<img width="1295" alt="Screenshot 2023-10-18 at 18 39 27" src="https://github.com/wasmCloud/wash/assets/3869136/4dbf86a2-6e00-4373-8f15-26e4194498ee">

**Comment by lachieh** [comment] 2023-10-19 12:44
May need to check the build to make sure that the latest version of the ui build is making it into the binary. It looks like they were built and committed recently but building off of main still generates different assets.

#925 updates the assets again, which should mean the next version of wash includes a working version. We can probably do a patch release for this, right @connorsmith256?

**Closed as completed** 2023-10-19 16:18 UTC
Labels: bug, help wanted
