### ISSUE TITLE
[BUG] Error with libcrypto despite having libssl-dev installed

### ISSUE THREAD

**Issue by bcpeinhardt** [wasmCloud/wash-archive#438] opened 2023-03-01 23:19 UTC
**Describe the bug**
I'm getting an error when running `wash up` 
```
=ERROR REPORT==== 1-Mar-2023::17:06:58.656499 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /home/<my-username>/.wash/downloads/v0.60.0/lib/crypto-5.1.2/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

```
Desipte having previously run `sudo apt-get install libssl-dev`

**To Reproduce**
Instructions for Ubuntu:
Install lbssl-dev: `sudo apt-get install libssl-dev`
Install wash with cargo: `cargo install wash-cli`
run `wash up`

**Expected behavior**
Not getting the missing lib-crypto error.

**Screenshots**
Here's a screenshot of my system info if it helps
![system_information](https://user-images.githubusercontent.com/61021968/222288751-831e8cd5-2fd0-4c36-87a1-4fa2f7a519ec.png)

**Environment (please complete the following information) **
 - OS: Ubuntu 22.04.1 LTS
 - Shell bash
 - wash 0.15.1

**Additional context**
I also encountered the error with the Ubuntu wash install.

**Comment by brooksmtownsend** [comment] 2023-03-02 16:11
Hey @bcpeinhardt ! This issue is actually a duplicate of #366 , and is a known problem with the wasmCloud host today. The host is built against a libcrypto version 1.1, while Ubuntu 22.04 has OpenSSL 3.0 installed. I'm going to close this issue just as we're tracking it in a different place, but please let me know and re-open if the workaround steps in #366 don't resolve your issue

**Closed as completed by brooksmtownsend** 2023-03-02 16:11 UTC
Labels: bug, help wanted

**Comment by bcpeinhardt** [comment] 2023-03-02 16:22
Yup just posting here to say installing libcrypto v1.1 worked like a charm :) Thank you!!

**Comment by brooksmtownsend** [comment] 2023-03-02 17:12
Awesome, thanks for going through the workaround @bcpeinhardt 🔥
